language: ruby
sudo: false
cache: bundler
before_install:
  - gem install bundler
script:
  - bundle exec rubocop
  - bundle exec rake test
rvm:
  - 2.5.0
  - 2.6.2
  - ruby-head
  - jruby-head
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
